### PR TITLE
Enable keymanager API server authentication

### PR DESCRIPTION
**Pull request by nflaig**
Enables keymanager API server authentication. Not sure if this is a strict requirement as it depends on how the API is exposed but even if it is just accessible internally should still protect it.

### CODE REVIEW

**Comment by alexpeterson91** [comment]
Hi @nflaig Lodestar hasnt completed its testing on dappnode, and all of it has been done on the prater client.  The prater configuration for Lodestar here https://github.com/dappnode/DAppNodePackage-Lodestar-Prater has been reviewed by ChainSafe's devs and approved, all parameters and the signer authentication.  Needed more additions to the web3signer and backend of the core etc too.  please refer to the prater repo for the proper configurations. The way we handle all ETH clients is completing the prater side testing first then copy configurations to mainnet and gnosis etc.  which is why this mainnet repo has not had anny real activity in a long time since all testing and modifications (more than 10 repos) is tracked by our internal project tracker.  Once the prater client is done (everything is actually merged and just needs to be tested (im clearing more space and spinning up more nodes to properly test since honestly lodestar has been ready to go for months now, just was very low on priority lists) we will be copying the working config to the other networks.

**Comment by nflaig** [comment]
Hi @alexpeterson91, thanks for clarifying how the process works. Should I close the other PRs which are not merged now and reopen them on the prater repository? If there is anything else I can help with let me know

**Comment by alexpeterson91** [comment]
> Hi @alexpeterson91, thanks for clarifying how the process works. Should I close the other PRs which are not merged now and reopen them on the prater repository? If there is anything else I can help with let me know

sorry for the delays ive had some major issues to deal with AFK in the last 2 weeks.  Catching back up and going through PRs and such now.
And yes it's best to just make any/all PRs in the prater package first as it was already ahead of this package and we like to start on goerli/prater testnet and then move onto mainnet and gnosis, but no need to close the ones opened here, they will be taken care of.

**Comment by nflaig** [comment]
> sorry for the delays ive had some major issues to deal with AFK in the last 2 weeks. Catching back up and going through PRs and such now.

no worries, thanks for all the reviews 👍 

> And yes it's best to just make any/all PRs in the prater package first as it was already ahead of this package and we like to start on goerli/prater testnet and then move onto mainnet and gnosis, but no need to close the ones opened here, they will be taken care of.

sounds good, I also set up a dappnode stack with the lodestar package to test on goerli, after merging all the PRs it should work now but I will do some further testing and open PRs if I find any issues.

**Comment by nflaig** [comment]
@alexpeterson91 just a quick update, running a bunch of validators now on goerli with the latest version of Lodestar prater package and it looks pretty stable.


This is my setup

image


Will keep this running for a while now to find potential issues, could also test with different EL client but I would not expect issues there

**Pull request merged**
